DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS favorites;

CREATE TABLE users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    user_email TEXT NOT NULL
);

CREATE TABLE favorites (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    setup TEXT NOT NULL,
    punchline TEXT NOT NULL,
    user_id INT REFERENCES users(id) ON DELETE SET NULL
);